name: SparseGaussians
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - plyfile
  - tqdm
  - python
  - pip
  - pip:
    - -e submodules/diff-gaussian-rasterization
    - -e submodules/simple-knn
