name: SparseGaussians
channel_priority: strict
channels:
  - nvidia/label/cuda-12.1.1
  - nvidia
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - cuda-toolkit
  - gxx_linux-64
  - glm
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - plyfile
  - tqdm
  - scipy
  - python
  - pip
  - pip:
    - -e submodules/diff-gaussian-rasterization
    - -e submodules/simple-knn
    # Deps from Dust3r:
    - roma
    - gradio
    - matplotlib
    - opencv-python
    - einops
    - trimesh
    - tensorboard
    - pyglet<2
    - huggingface-hub[torch]>=0.22
